# Generated by Django 3.2.9 on 2021-11-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='remark',
        ),
    ]
